"""add_quantity_on_hand_to_products

Revision ID: 4b33bd2cca5a
Revises: b0727c792c75
Create Date: 2026-06-10 22:22:54.470920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b33bd2cca5a'
down_revision: Union[str, None] = 'b0727c792c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_on_hand', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity_on_hand')
    # ### end Alembic commands ###
